<?php

namespace App\Services;

use Exception;

class WorklistService
{
    protected string $worklistDir;
    protected string $orthancHost;
    protected int    $orthancPort;

    public function __construct()
    {
        $this->worklistDir = env('WORKLIST_DIR', '/var/lib/orthanc/worklists');
        $this->orthancHost = env('ORTHANC_HOST', '192.168.0.106');
        $this->orthancPort = env('ORTHANC_PORT', 8042);
    }

    /**
     * Generate file .wl dan simpan ke folder Orthanc
     */
    public function createOrder(array $data): string
    {
        $acc      = $data['AccessionNumber'];
        $dumpPath = "/tmp/{$acc}.dump";
        $wlPath   = "{$this->worklistDir}/{$acc}.wl";

        // Cek duplikat
        if (file_exists($wlPath)) {
            throw new Exception("AccessionNumber '{$acc}' sudah ada.");
        }

        // Buat konten dump
        $dump = $this->buildDump($data);

        // Tulis file dump
        file_put_contents($dumpPath, $dump);

        // Convert ke .wl pakai dcmtk
        $output     = [];
        $returnCode = 0;
        exec("dump2dcm {$dumpPath} {$wlPath} 2>&1", $output, $returnCode);

        // Hapus file dump sementara
        @unlink($dumpPath);

        if ($returnCode !== 0) {
            throw new Exception("dump2dcm error: " . implode("\n", $output));
        }

        return $wlPath;
    }

    /**
     * List semua order yang ada di folder worklist
     */
    public function listOrders(): array
    {
        $files  = glob("{$this->worklistDir}/*.wl") ?: [];
        $orders = [];

        foreach ($files as $file) {
            $acc      = pathinfo($file, PATHINFO_FILENAME);
            $orders[] = [
                'AccessionNumber' => $acc,
                'file'            => $file,
                'size_bytes'      => filesize($file),
                'created_at'      => date('Y-m-d H:i:s', filectime($file)),
            ];
        }

        return $orders;
    }

    /**
     * Hapus order berdasarkan AccessionNumber
     */
    public function deleteOrder(string $acc): void
    {
        $wlPath = "{$this->worklistDir}/{$acc}.wl";

        if (!file_exists($wlPath)) {
            throw new Exception("Order '{$acc}' tidak ditemukan.");
        }

        unlink($wlPath);
    }

    /**
     * Health check — cek folder worklist & dcmtk
     */
    public function health(): array
    {
        $dcmtkCheck = [];
        $dcmtkCode  = 0;
        exec("which dump2dcm 2>&1", $dcmtkCheck, $dcmtkCode);

        return [
            'worklist_dir'       => $this->worklistDir,
            'worklist_dir_exists'=> is_dir($this->worklistDir),
            'worklist_writable'  => is_writable($this->worklistDir),
            'dcmtk_available'    => $dcmtkCode === 0,
            'orthanc'            => "http://{$this->orthancHost}:{$this->orthancPort}",
            'total_orders'       => count(glob("{$this->worklistDir}/*.wl") ?: []),
        ];
    }

    /**
     * Build konten file .dump
     */
    private function buildDump(array $data): string
    {
        $acc = $data['AccessionNumber'];

        return <<<DUMP
# DICOM Worklist - Generated by Laravel Middleware
(0008,0005) CS [ISO_IR 6]
(0008,0050) SH [{$acc}]
(0010,0010) PN [{$data['PatientName']}]
(0010,0020) LO [{$data['PatientID']}]
(0010,0030) DA [{$data['PatientBirthDate']}]
(0010,0040) CS [{$data['PatientSex']}]
(0020,000d) UI [1.2.840.10008.5.1.4.1.2.1.{$acc}]
(0032,1060) LO [{$data['RequestedProcedureDescription']}]
(0040,1001) SH [RP-{$acc}]
(0040,0100) SQ
(fffe,e000) na
(0008,0060) CS [{$data['Modality']}]
(0040,0001) AE [{$data['ScheduledAET']}]
(0040,0002) DA [{$data['ScheduledDate']}]
(0040,0003) TM [{$data['ScheduledTime']}]
(0040,0006) PN [{$data['ScheduledPhysician']}]
(0040,0007) LO [{$data['RequestedProcedureDescription']}]
(0040,0009) SH [SPS-{$acc}]
(fffe,e00d)
(fffe,e0dd)
DUMP;
    }
}